export type ThemeName =
  | 'midnight'
  | 'light'
  | 'phosphor'
  | 'dracula'
  | 'nord'
  | 'solarized-dark'
  | 'catppuccin-mocha'
  | 'tokyo-night'
  | 'gruvbox-dark'
  | 'one-dark'
  | 'monokai'
  | 'ayu-dark'
  | 'rose-pine'
  | 'monochrome'
  | 'vesper'
  | 'kanagawa'
  | 'everforest'
  | 'synthwave'
  | 'flexoki'
  | 'night-owl'
  | 'panda'
  | 'horizon'
  | 'cobalt2'
  | 'material-ocean'
  | 'hack-the-box'
  | 'palenight'
  | 'darcula'
  | 'iceberg'
  | 'github-dark'
  | 'github-light'
  | 'solarized-light'
  | 'catppuccin-latte'
  | 'ayu-light'
  | 'rose-pine-dawn'
  | 'gruvbox-light'
  | 'one-light'
  | 'everforest-light'
  | 'nord-light'
  | 'catppuccin-frappe'
  | 'catppuccin-macchiato'
  | 'rose-pine-moon';

export interface Theme {
  name: ThemeName;
  label: string;
  colors: Record<string, string>;
}

export const themes: Record<ThemeName, Theme> = {
  midnight: {
    name: 'midnight',
    label: 'Midnight',
    colors: {
      '--color-background':        '#0a0e14',
      '--color-foreground':        '#B3B1AD',
      '--color-card':              '#0d1117',
      '--color-card-foreground':   '#B3B1AD',
      '--color-primary':           '#39BAE6',
      '--color-primary-foreground':'#0a0e14',
      '--color-secondary':         '#151b23',
      '--color-secondary-foreground':'#B3B1AD',
      '--color-muted':             '#151b23',
      '--color-muted-foreground':  '#6c7380',
      '--color-destructive':       '#FF3333',
      '--color-border':            '#1e2530',
      '--color-input':             '#1e2530',
      '--color-ring':              '#39BAE6',
      '--color-green':             '#7FD962',
      '--color-red':               '#FF3333',
      '--color-orange':            '#FF8F40',
      '--color-purple':            '#D2A6FF',
      '--color-scrollbar':         '#1e2530',
      '--color-scrollbar-hover':   '#2d3848',
    },
  },
  light: {
    name: 'light',
    label: 'Light',
    colors: {
      '--color-background':        '#FAFAFA',
      '--color-foreground':        '#1a1a1a',
      '--color-card':              '#FFFFFF',
      '--color-card-foreground':   '#1a1a1a',
      '--color-primary':           '#4F46E5',
      '--color-primary-foreground':'#FFFFFF',
      '--color-secondary':         '#F3F4F6',
      '--color-secondary-foreground':'#1a1a1a',
      '--color-muted':             '#F3F4F6',
      '--color-muted-foreground':  '#6B7280',
      '--color-destructive':       '#DC2626',
      '--color-border':            '#E5E7EB',
      '--color-input':             '#E5E7EB',
      '--color-ring':              '#4F46E5',
      '--color-green':             '#16A34A',
      '--color-red':               '#DC2626',
      '--color-orange':            '#D97706',
      '--color-purple':            '#7C3AED',
      '--color-scrollbar':         '#D1D5DB',
      '--color-scrollbar-hover':   '#9CA3AF',
    },
  },
  phosphor: {
    name: 'phosphor',
    label: 'Phosphor',
    colors: {
      '--color-background':        '#080808',
      '--color-foreground':        '#88CC88',
      '--color-card':              '#0d120d',
      '--color-card-foreground':   '#88CC88',
      '--color-primary':           '#00FF41',
      '--color-primary-foreground':'#080808',
      '--color-secondary':         '#0f160f',
      '--color-secondary-foreground':'#88CC88',
      '--color-muted':             '#0f160f',
      '--color-muted-foreground':  '#4a6a4a',
      '--color-destructive':       '#FF3333',
      '--color-border':            '#1a2e1a',
      '--color-input':             '#1a2e1a',
      '--color-ring':              '#00FF41',
      '--color-green':             '#00FF41',
      '--color-red':               '#FF3333',
      '--color-orange':            '#CCAA33',
      '--color-purple':            '#6B8E6B',
      '--color-scrollbar':         '#1a2e1a',
      '--color-scrollbar-hover':   '#2a4a2a',
    },
  },
  dracula: {
    name: 'dracula',
    label: 'Dracula',
    colors: {
      '--color-background':        '#282A36',
      '--color-foreground':        '#F8F8F2',
      '--color-card':              '#21222C',
      '--color-card-foreground':   '#F8F8F2',
      '--color-primary':           '#BD93F9',
      '--color-primary-foreground':'#282A36',
      '--color-secondary':         '#343746',
      '--color-secondary-foreground':'#F8F8F2',
      '--color-muted':             '#343746',
      '--color-muted-foreground':  '#6272A4',
      '--color-destructive':       '#FF5555',
      '--color-border':            '#44475A',
      '--color-input':             '#44475A',
      '--color-ring':              '#BD93F9',
      '--color-green':             '#50FA7B',
      '--color-red':               '#FF5555',
      '--color-orange':            '#FFB86C',
      '--color-purple':            '#BD93F9',
      '--color-scrollbar':         '#44475A',
      '--color-scrollbar-hover':   '#6272A4',
    },
  },
  nord: {
    name: 'nord',
    label: 'Nord',
    colors: {
      '--color-background':        '#2E3440',
      '--color-foreground':        '#D8DEE9',
      '--color-card':              '#3B4252',
      '--color-card-foreground':   '#D8DEE9',
      '--color-primary':           '#88C0D0',
      '--color-primary-foreground':'#2E3440',
      '--color-secondary':         '#434C5E',
      '--color-secondary-foreground':'#D8DEE9',
      '--color-muted':             '#434C5E',
      '--color-muted-foreground':  '#7B88A1',
      '--color-destructive':       '#BF616A',
      '--color-border':            '#4C566A',
      '--color-input':             '#4C566A',
      '--color-ring':              '#88C0D0',
      '--color-green':             '#A3BE8C',
      '--color-red':               '#BF616A',
      '--color-orange':            '#D08770',
      '--color-purple':            '#B48EAD',
      '--color-scrollbar':         '#4C566A',
      '--color-scrollbar-hover':   '#5E6779',
    },
  },
  'solarized-dark': {
    name: 'solarized-dark',
    label: 'Solarized Dark',
    colors: {
      '--color-background':        '#002B36',
      '--color-foreground':        '#839496',
      '--color-card':              '#073642',
      '--color-card-foreground':   '#839496',
      '--color-primary':           '#268BD2',
      '--color-primary-foreground':'#FDF6E3',
      '--color-secondary':         '#0A3E4A',
      '--color-secondary-foreground':'#839496',
      '--color-muted':             '#0A3E4A',
      '--color-muted-foreground':  '#586E75',
      '--color-destructive':       '#DC322F',
      '--color-border':            '#0E4F5C',
      '--color-input':             '#0E4F5C',
      '--color-ring':              '#268BD2',
      '--color-green':             '#859900',
      '--color-red':               '#DC322F',
      '--color-orange':            '#CB4B16',
      '--color-purple':            '#6C71C4',
      '--color-scrollbar':         '#0E4F5C',
      '--color-scrollbar-hover':   '#1A6070',
    },
  },
  'catppuccin-mocha': {
    name: 'catppuccin-mocha',
    label: 'Catppuccin Mocha',
    colors: {
      '--color-background':        '#1E1E2E',
      '--color-foreground':        '#CDD6F4',
      '--color-card':              '#181825',
      '--color-card-foreground':   '#CDD6F4',
      '--color-primary':           '#CBA6F7',
      '--color-primary-foreground':'#1E1E2E',
      '--color-secondary':         '#313244',
      '--color-secondary-foreground':'#CDD6F4',
      '--color-muted':             '#313244',
      '--color-muted-foreground':  '#6C7086',
      '--color-destructive':       '#F38BA8',
      '--color-border':            '#45475A',
      '--color-input':             '#45475A',
      '--color-ring':              '#CBA6F7',
      '--color-green':             '#A6E3A1',
      '--color-red':               '#F38BA8',
      '--color-orange':            '#FAB387',
      '--color-purple':            '#CBA6F7',
      '--color-scrollbar':         '#45475A',
      '--color-scrollbar-hover':   '#585B70',
    },
  },
  'tokyo-night': {
    name: 'tokyo-night',
    label: 'Tokyo Night',
    colors: {
      '--color-background':        '#1A1B26',
      '--color-foreground':        '#A9B1D6',
      '--color-card':              '#16161E',
      '--color-card-foreground':   '#A9B1D6',
      '--color-primary':           '#7AA2F7',
      '--color-primary-foreground':'#1A1B26',
      '--color-secondary':         '#24283B',
      '--color-secondary-foreground':'#A9B1D6',
      '--color-muted':             '#24283B',
      '--color-muted-foreground':  '#565F89',
      '--color-destructive':       '#F7768E',
      '--color-border':            '#2F3549',
      '--color-input':             '#2F3549',
      '--color-ring':              '#7AA2F7',
      '--color-green':             '#9ECE6A',
      '--color-red':               '#F7768E',
      '--color-orange':            '#FF9E64',
      '--color-purple':            '#BB9AF7',
      '--color-scrollbar':         '#2F3549',
      '--color-scrollbar-hover':   '#414868',
    },
  },
  'gruvbox-dark': {
    name: 'gruvbox-dark',
    label: 'Gruvbox Dark',
    colors: {
      '--color-background':        '#282828',
      '--color-foreground':        '#EBDBB2',
      '--color-card':              '#1D2021',
      '--color-card-foreground':   '#EBDBB2',
      '--color-primary':           '#FABD2F',
      '--color-primary-foreground':'#282828',
      '--color-secondary':         '#3C3836',
      '--color-secondary-foreground':'#EBDBB2',
      '--color-muted':             '#3C3836',
      '--color-muted-foreground':  '#928374',
      '--color-destructive':       '#FB4934',
      '--color-border':            '#504945',
      '--color-input':             '#504945',
      '--color-ring':              '#FABD2F',
      '--color-green':             '#B8BB26',
      '--color-red':               '#FB4934',
      '--color-orange':            '#FE8019',
      '--color-purple':            '#D3869B',
      '--color-scrollbar':         '#504945',
      '--color-scrollbar-hover':   '#665C54',
    },
  },
  'one-dark': {
    name: 'one-dark',
    label: 'One Dark',
    colors: {
      '--color-background':        '#282C34',
      '--color-foreground':        '#ABB2BF',
      '--color-card':              '#21252B',
      '--color-card-foreground':   '#ABB2BF',
      '--color-primary':           '#61AFEF',
      '--color-primary-foreground':'#282C34',
      '--color-secondary':         '#2C313A',
      '--color-secondary-foreground':'#ABB2BF',
      '--color-muted':             '#2C313A',
      '--color-muted-foreground':  '#5C6370',
      '--color-destructive':       '#E06C75',
      '--color-border':            '#3E4451',
      '--color-input':             '#3E4451',
      '--color-ring':              '#61AFEF',
      '--color-green':             '#98C379',
      '--color-red':               '#E06C75',
      '--color-orange':            '#D19A66',
      '--color-purple':            '#C678DD',
      '--color-scrollbar':         '#3E4451',
      '--color-scrollbar-hover':   '#4B5263',
    },
  },
  monokai: {
    name: 'monokai',
    label: 'Monokai Pro',
    colors: {
      '--color-background':        '#2D2A2E',
      '--color-foreground':        '#FCFCFA',
      '--color-card':              '#221F22',
      '--color-card-foreground':   '#FCFCFA',
      '--color-primary':           '#FFD866',
      '--color-primary-foreground':'#2D2A2E',
      '--color-secondary':         '#3A373E',
      '--color-secondary-foreground':'#FCFCFA',
      '--color-muted':             '#3A373E',
      '--color-muted-foreground':  '#727072',
      '--color-destructive':       '#FF6188',
      '--color-border':            '#423F46',
      '--color-input':             '#423F46',
      '--color-ring':              '#FFD866',
      '--color-green':             '#A9DC76',
      '--color-red':               '#FF6188',
      '--color-orange':            '#FC9867',
      '--color-purple':            '#AB9DF2',
      '--color-scrollbar':         '#423F46',
      '--color-scrollbar-hover':   '#5B5860',
    },
  },
  'ayu-dark': {
    name: 'ayu-dark',
    label: 'Ayu Dark',
    colors: {
      '--color-background':        '#0B0E14',
      '--color-foreground':        '#BFBDB6',
      '--color-card':              '#0D1017',
      '--color-card-foreground':   '#BFBDB6',
      '--color-primary':           '#E6B450',
      '--color-primary-foreground':'#0B0E14',
      '--color-secondary':         '#151820',
      '--color-secondary-foreground':'#BFBDB6',
      '--color-muted':             '#151820',
      '--color-muted-foreground':  '#565B66',
      '--color-destructive':       '#D95757',
      '--color-border':            '#1C2029',
      '--color-input':             '#1C2029',
      '--color-ring':              '#E6B450',
      '--color-green':             '#7FD962',
      '--color-red':               '#D95757',
      '--color-orange':            '#FF8F40',
      '--color-purple':            '#D2A6FF',
      '--color-scrollbar':         '#1C2029',
      '--color-scrollbar-hover':   '#2A303C',
    },
  },
  'rose-pine': {
    name: 'rose-pine',
    label: 'Rosé Pine',
    colors: {
      '--color-background':        '#191724',
      '--color-foreground':        '#E0DEF4',
      '--color-card':              '#1F1D2E',
      '--color-card-foreground':   '#E0DEF4',
      '--color-primary':           '#EBBCBA',
      '--color-primary-foreground':'#191724',
      '--color-secondary':         '#26233A',
      '--color-secondary-foreground':'#E0DEF4',
      '--color-muted':             '#26233A',
      '--color-muted-foreground':  '#6E6A86',
      '--color-destructive':       '#EB6F92',
      '--color-border':            '#2A2740',
      '--color-input':             '#2A2740',
      '--color-ring':              '#EBBCBA',
      '--color-green':             '#31748F',
      '--color-red':               '#EB6F92',
      '--color-orange':            '#F6C177',
      '--color-purple':            '#C4A7E7',
      '--color-scrollbar':         '#2A2740',
      '--color-scrollbar-hover':   '#3A3654',
    },
  },
  monochrome: {
    name: 'monochrome',
    label: 'Monochrome',
    colors: {
      '--color-background':        '#0A0A0A',
      '--color-foreground':        '#C0C0C0',
      '--color-card':              '#111111',
      '--color-card-foreground':   '#C0C0C0',
      '--color-primary':           '#E0E0E0',
      '--color-primary-foreground':'#0A0A0A',
      '--color-secondary':         '#181818',
      '--color-secondary-foreground':'#C0C0C0',
      '--color-muted':             '#181818',
      '--color-muted-foreground':  '#666666',
      '--color-destructive':       '#B05050',
      '--color-border':            '#222222',
      '--color-input':             '#222222',
      '--color-ring':              '#E0E0E0',
      '--color-green':             '#6B9B6B',
      '--color-red':               '#B05050',
      '--color-orange':            '#B09060',
      '--color-purple':            '#8A8A9A',
      '--color-scrollbar':         '#222222',
      '--color-scrollbar-hover':   '#3A3A3A',
    },
  },
  vesper: {
    name: 'vesper',
    label: 'Vesper',
    colors: {
      '--color-background':        '#101010',
      '--color-foreground':        '#FFFFFF',
      '--color-card':              '#1A1A1A',
      '--color-card-foreground':   '#FFFFFF',
      '--color-primary':           '#FFC799',
      '--color-primary-foreground':'#101010',
      '--color-secondary':         '#252525',
      '--color-secondary-foreground':'#FFFFFF',
      '--color-muted':             '#252525',
      '--color-muted-foreground':  '#666666',
      '--color-destructive':       '#F44747',
      '--color-border':            '#2A2A2A',
      '--color-input':             '#2A2A2A',
      '--color-ring':              '#FFC799',
      '--color-green':             '#A8CC7E',
      '--color-red':               '#F44747',
      '--color-orange':            '#FFC799',
      '--color-purple':            '#C4A4D4',
      '--color-scrollbar':         '#2A2A2A',
      '--color-scrollbar-hover':   '#3A3A3A',
    },
  },
  kanagawa: {
    name: 'kanagawa',
    label: 'Kanagawa',
    colors: {
      '--color-background':        '#1F1F28',
      '--color-foreground':        '#DCD7BA',
      '--color-card':              '#16161D',
      '--color-card-foreground':   '#DCD7BA',
      '--color-primary':           '#7FB4CA',
      '--color-primary-foreground':'#1F1F28',
      '--color-secondary':         '#2A2A37',
      '--color-secondary-foreground':'#DCD7BA',
      '--color-muted':             '#2A2A37',
      '--color-muted-foreground':  '#727169',
      '--color-destructive':       '#E46876',
      '--color-border':            '#363646',
      '--color-input':             '#363646',
      '--color-ring':              '#7FB4CA',
      '--color-green':             '#98BB6C',
      '--color-red':               '#E46876',
      '--color-orange':            '#FFA066',
      '--color-purple':            '#957FB8',
      '--color-scrollbar':         '#363646',
      '--color-scrollbar-hover':   '#54546D',
    },
  },
  everforest: {
    name: 'everforest',
    label: 'Everforest',
    colors: {
      '--color-background':        '#2D353B',
      '--color-foreground':        '#D3C6AA',
      '--color-card':              '#272E33',
      '--color-card-foreground':   '#D3C6AA',
      '--color-primary':           '#A7C080',
      '--color-primary-foreground':'#2D353B',
      '--color-secondary':         '#343F44',
      '--color-secondary-foreground':'#D3C6AA',
      '--color-muted':             '#343F44',
      '--color-muted-foreground':  '#859289',
      '--color-destructive':       '#E67E80',
      '--color-border':            '#3D484D',
      '--color-input':             '#3D484D',
      '--color-ring':              '#A7C080',
      '--color-green':             '#A7C080',
      '--color-red':               '#E67E80',
      '--color-orange':            '#E69875',
      '--color-purple':            '#D699B6',
      '--color-scrollbar':         '#3D484D',
      '--color-scrollbar-hover':   '#4A555B',
    },
  },
  synthwave: {
    name: 'synthwave',
    label: "Synthwave '84",
    colors: {
      '--color-background':        '#0A0014',
      '--color-foreground':        '#F0E6FF',
      '--color-card':              '#0F001A',
      '--color-card-foreground':   '#F0E6FF',
      '--color-primary':           '#FF7EDB',
      '--color-primary-foreground':'#0A0014',
      '--color-secondary':         '#160025',
      '--color-secondary-foreground':'#F0E6FF',
      '--color-muted':             '#160025',
      '--color-muted-foreground':  '#6B5A8E',
      '--color-destructive':       '#FF4444',
      '--color-border':            '#2B0042',
      '--color-input':             '#2B0042',
      '--color-ring':              '#FF7EDB',
      '--color-green':             '#72F1B8',
      '--color-red':               '#FF4444',
      '--color-orange':            '#FE4450',
      '--color-purple':            '#BE8FFF',
      '--color-scrollbar':         '#2B0042',
      '--color-scrollbar-hover':   '#420060',
    },
  },
  flexoki: {
    name: 'flexoki',
    label: 'Flexoki',
    colors: {
      '--color-background':        '#100F0F',
      '--color-foreground':        '#CECDC3',
      '--color-card':              '#1C1B1A',
      '--color-card-foreground':   '#CECDC3',
      '--color-primary':           '#879A39',
      '--color-primary-foreground':'#FFFCF0',
      '--color-secondary':         '#282726',
      '--color-secondary-foreground':'#CECDC3',
      '--color-muted':             '#282726',
      '--color-muted-foreground':  '#878580',
      '--color-destructive':       '#D14D41',
      '--color-border':            '#343331',
      '--color-input':             '#343331',
      '--color-ring':              '#879A39',
      '--color-green':             '#879A39',
      '--color-red':               '#D14D41',
      '--color-orange':            '#DA702C',
      '--color-purple':            '#8B7EC8',
      '--color-scrollbar':         '#343331',
      '--color-scrollbar-hover':   '#403E3C',
    },
  },
  'night-owl': {
    name: 'night-owl',
    label: 'Night Owl',
    colors: {
      '--color-background':        '#011627',
      '--color-foreground':        '#D6DEEB',
      '--color-card':              '#01111D',
      '--color-card-foreground':   '#D6DEEB',
      '--color-primary':           '#82AAFF',
      '--color-primary-foreground':'#011627',
      '--color-secondary':         '#0B2942',
      '--color-secondary-foreground':'#D6DEEB',
      '--color-muted':             '#0B2942',
      '--color-muted-foreground':  '#4D6273',
      '--color-destructive':       '#EF5350',
      '--color-border':            '#0E3A5C',
      '--color-input':             '#0E3A5C',
      '--color-ring':              '#82AAFF',
      '--color-green':             '#22DA6E',
      '--color-red':               '#EF5350',
      '--color-orange':            '#FFCB8B',
      '--color-purple':            '#C792EA',
      '--color-scrollbar':         '#0E3A5C',
      '--color-scrollbar-hover':   '#1A5070',
    },
  },
  panda: {
    name: 'panda',
    label: 'Panda',
    colors: {
      '--color-background':        '#292A2B',
      '--color-foreground':        '#E6E6E6',
      '--color-card':              '#232425',
      '--color-card-foreground':   '#E6E6E6',
      '--color-primary':           '#FF75B5',
      '--color-primary-foreground':'#292A2B',
      '--color-secondary':         '#323334',
      '--color-secondary-foreground':'#E6E6E6',
      '--color-muted':             '#323334',
      '--color-muted-foreground':  '#676B79',
      '--color-destructive':       '#FF2C6D',
      '--color-border':            '#3D3E3F',
      '--color-input':             '#3D3E3F',
      '--color-ring':              '#FF75B5',
      '--color-green':             '#19F9D8',
      '--color-red':               '#FF2C6D',
      '--color-orange':            '#FFCC95',
      '--color-purple':            '#B084EB',
      '--color-scrollbar':         '#3D3E3F',
      '--color-scrollbar-hover':   '#505152',
    },
  },
  horizon: {
    name: 'horizon',
    label: 'Horizon',
    colors: {
      '--color-background':        '#1C1E26',
      '--color-foreground':        '#D5D8DA',
      '--color-card':              '#16181F',
      '--color-card-foreground':   '#D5D8DA',
      '--color-primary':           '#E95378',
      '--color-primary-foreground':'#1C1E26',
      '--color-secondary':         '#232530',
      '--color-secondary-foreground':'#D5D8DA',
      '--color-muted':             '#232530',
      '--color-muted-foreground':  '#4E505E',
      '--color-destructive':       '#E95378',
      '--color-border':            '#2E303E',
      '--color-input':             '#2E303E',
      '--color-ring':              '#E95378',
      '--color-green':             '#09F7A0',
      '--color-red':               '#E95378',
      '--color-orange':            '#FAB795',
      '--color-purple':            '#B877DB',
      '--color-scrollbar':         '#2E303E',
      '--color-scrollbar-hover':   '#3E4050',
    },
  },
  cobalt2: {
    name: 'cobalt2',
    label: 'Cobalt2',
    colors: {
      '--color-background':        '#193549',
      '--color-foreground':        '#FFFFFF',
      '--color-card':              '#122738',
      '--color-card-foreground':   '#FFFFFF',
      '--color-primary':           '#FFC600',
      '--color-primary-foreground':'#193549',
      '--color-secondary':         '#1D3F56',
      '--color-secondary-foreground':'#FFFFFF',
      '--color-muted':             '#1D3F56',
      '--color-muted-foreground':  '#4B6981',
      '--color-destructive':       '#FF628C',
      '--color-border':            '#234E6C',
      '--color-input':             '#234E6C',
      '--color-ring':              '#FFC600',
      '--color-green':             '#3AD900',
      '--color-red':               '#FF628C',
      '--color-orange':            '#FF9D00',
      '--color-purple':            '#9EFFFF',
      '--color-scrollbar':         '#234E6C',
      '--color-scrollbar-hover':   '#336080',
    },
  },
  'material-ocean': {
    name: 'material-ocean',
    label: 'Material Ocean',
    colors: {
      '--color-background':        '#0F111A',
      '--color-foreground':        '#8F93A2',
      '--color-card':              '#090B10',
      '--color-card-foreground':   '#8F93A2',
      '--color-primary':           '#84FFFF',
      '--color-primary-foreground':'#0F111A',
      '--color-secondary':         '#181A23',
      '--color-secondary-foreground':'#8F93A2',
      '--color-muted':             '#181A23',
      '--color-muted-foreground':  '#464B5D',
      '--color-destructive':       '#FF5370',
      '--color-border':            '#1F2233',
      '--color-input':             '#1F2233',
      '--color-ring':              '#84FFFF',
      '--color-green':             '#C3E88D',
      '--color-red':               '#FF5370',
      '--color-orange':            '#F78C6C',
      '--color-purple':            '#C792EA',
      '--color-scrollbar':         '#1F2233',
      '--color-scrollbar-hover':   '#2D3047',
    },
  },
  'hack-the-box': {
    name: 'hack-the-box',
    label: 'Hack The Box',
    colors: {
      '--color-background':        '#141D2B',
      '--color-foreground':        '#A4B1CD',
      '--color-card':              '#0D1520',
      '--color-card-foreground':   '#A4B1CD',
      '--color-primary':           '#9FEF00',
      '--color-primary-foreground':'#141D2B',
      '--color-secondary':         '#1A2537',
      '--color-secondary-foreground':'#A4B1CD',
      '--color-muted':             '#1A2537',
      '--color-muted-foreground':  '#4A5568',
      '--color-destructive':       '#FF5555',
      '--color-border':            '#1E3050',
      '--color-input':             '#1E3050',
      '--color-ring':              '#9FEF00',
      '--color-green':             '#9FEF00',
      '--color-red':               '#FF5555',
      '--color-orange':            '#FFAF00',
      '--color-purple':            '#A98CF4',
      '--color-scrollbar':         '#1E3050',
      '--color-scrollbar-hover':   '#2A4068',
    },
  },
  palenight: {
    name: 'palenight',
    label: 'Palenight',
    colors: {
      '--color-background':        '#292D3E',
      '--color-foreground':        '#A6ACCD',
      '--color-card':              '#1E212E',
      '--color-card-foreground':   '#A6ACCD',
      '--color-primary':           '#C792EA',
      '--color-primary-foreground':'#292D3E',
      '--color-secondary':         '#34384F',
      '--color-secondary-foreground':'#A6ACCD',
      '--color-muted':             '#34384F',
      '--color-muted-foreground':  '#676E95',
      '--color-destructive':       '#FF5370',
      '--color-border':            '#3C415C',
      '--color-input':             '#3C415C',
      '--color-ring':              '#C792EA',
      '--color-green':             '#C3E88D',
      '--color-red':               '#FF5370',
      '--color-orange':            '#F78C6C',
      '--color-purple':            '#C792EA',
      '--color-scrollbar':         '#3C415C',
      '--color-scrollbar-hover':   '#4E5370',
    },
  },
  darcula: {
    name: 'darcula',
    label: 'Darcula',
    colors: {
      '--color-background':        '#2B2B2B',
      '--color-foreground':        '#A9B7C6',
      '--color-card':              '#1E1E1E',
      '--color-card-foreground':   '#A9B7C6',
      '--color-primary':           '#FFC66D',
      '--color-primary-foreground':'#2B2B2B',
      '--color-secondary':         '#3C3F41',
      '--color-secondary-foreground':'#A9B7C6',
      '--color-muted':             '#3C3F41',
      '--color-muted-foreground':  '#606366',
      '--color-destructive':       '#FF5555',
      '--color-border':            '#4B4B4B',
      '--color-input':             '#4B4B4B',
      '--color-ring':              '#FFC66D',
      '--color-green':             '#6A8759',
      '--color-red':               '#FF5555',
      '--color-orange':            '#CC7832',
      '--color-purple':            '#9876AA',
      '--color-scrollbar':         '#4B4B4B',
      '--color-scrollbar-hover':   '#5E5E5E',
    },
  },
  iceberg: {
    name: 'iceberg',
    label: 'Iceberg',
    colors: {
      '--color-background':        '#161821',
      '--color-foreground':        '#C6C8D1',
      '--color-card':              '#0F1117',
      '--color-card-foreground':   '#C6C8D1',
      '--color-primary':           '#84A0C6',
      '--color-primary-foreground':'#161821',
      '--color-secondary':         '#1E2132',
      '--color-secondary-foreground':'#C6C8D1',
      '--color-muted':             '#1E2132',
      '--color-muted-foreground':  '#444B71',
      '--color-destructive':       '#E27878',
      '--color-border':            '#2A2F45',
      '--color-input':             '#2A2F45',
      '--color-ring':              '#84A0C6',
      '--color-green':             '#B4BE82',
      '--color-red':               '#E27878',
      '--color-orange':            '#E2A478',
      '--color-purple':            '#A093C7',
      '--color-scrollbar':         '#2A2F45',
      '--color-scrollbar-hover':   '#3D4466',
    },
  },
  'github-dark': {
    name: 'github-dark',
    label: 'GitHub Dark',
    colors: {
      '--color-background':        '#0D1117',
      '--color-foreground':        '#E6EDF3',
      '--color-card':              '#161B22',
      '--color-card-foreground':   '#E6EDF3',
      '--color-primary':           '#58A6FF',
      '--color-primary-foreground':'#0D1117',
      '--color-secondary':         '#21262D',
      '--color-secondary-foreground':'#E6EDF3',
      '--color-muted':             '#21262D',
      '--color-muted-foreground':  '#8B949E',
      '--color-destructive':       '#F85149',
      '--color-border':            '#30363D',
      '--color-input':             '#30363D',
      '--color-ring':              '#58A6FF',
      '--color-green':             '#3FB950',
      '--color-red':               '#F85149',
      '--color-orange':            '#D29922',
      '--color-purple':            '#BC8CFF',
      '--color-scrollbar':         '#30363D',
      '--color-scrollbar-hover':   '#484F58',
    },
  },

  /* ── Light themes ─────────────────────────────────────── */

  'github-light': {
    name: 'github-light',
    label: 'GitHub Light',
    colors: {
      '--color-background':        '#FFFFFF',
      '--color-foreground':        '#1F2328',
      '--color-card':              '#FFFFFF',
      '--color-card-foreground':   '#1F2328',
      '--color-primary':           '#0969DA',
      '--color-primary-foreground':'#FFFFFF',
      '--color-secondary':         '#F6F8FA',
      '--color-secondary-foreground':'#1F2328',
      '--color-muted':             '#F6F8FA',
      '--color-muted-foreground':  '#656D76',
      '--color-destructive':       '#CF222E',
      '--color-border':            '#D1D9E0',
      '--color-input':             '#D1D9E0',
      '--color-ring':              '#0969DA',
      '--color-green':             '#1A7F37',
      '--color-red':               '#CF222E',
      '--color-orange':            '#BF8700',
      '--color-purple':            '#8250DF',
      '--color-scrollbar':         '#D1D9E0',
      '--color-scrollbar-hover':   '#B0B8C1',
    },
  },
  'solarized-light': {
    name: 'solarized-light',
    label: 'Solarized Light',
    colors: {
      '--color-background':        '#FDF6E3',
      '--color-foreground':        '#657B83',
      '--color-card':              '#EEE8D5',
      '--color-card-foreground':   '#586E75',
      '--color-primary':           '#268BD2',
      '--color-primary-foreground':'#FDF6E3',
      '--color-secondary':         '#EEE8D5',
      '--color-secondary-foreground':'#657B83',
      '--color-muted':             '#EEE8D5',
      '--color-muted-foreground':  '#93A1A1',
      '--color-destructive':       '#DC322F',
      '--color-border':            '#D3CBB7',
      '--color-input':             '#D3CBB7',
      '--color-ring':              '#268BD2',
      '--color-green':             '#859900',
      '--color-red':               '#DC322F',
      '--color-orange':            '#CB4B16',
      '--color-purple':            '#6C71C4',
      '--color-scrollbar':         '#D3CBB7',
      '--color-scrollbar-hover':   '#B8B09A',
    },
  },
  'catppuccin-latte': {
    name: 'catppuccin-latte',
    label: 'Catppuccin Latte',
    colors: {
      '--color-background':        '#EFF1F5',
      '--color-foreground':        '#4C4F69',
      '--color-card':              '#E6E9EF',
      '--color-card-foreground':   '#4C4F69',
      '--color-primary':           '#8839EF',
      '--color-primary-foreground':'#EFF1F5',
      '--color-secondary':         '#DCE0E8',
      '--color-secondary-foreground':'#4C4F69',
      '--color-muted':             '#DCE0E8',
      '--color-muted-foreground':  '#8C8FA1',
      '--color-destructive':       '#D20F39',
      '--color-border':            '#CCD0DA',
      '--color-input':             '#CCD0DA',
      '--color-ring':              '#8839EF',
      '--color-green':             '#40A02B',
      '--color-red':               '#D20F39',
      '--color-orange':            '#FE640B',
      '--color-purple':            '#8839EF',
      '--color-scrollbar':         '#CCD0DA',
      '--color-scrollbar-hover':   '#ACB0BE',
    },
  },
  'ayu-light': {
    name: 'ayu-light',
    label: 'Ayu Light',
    colors: {
      '--color-background':        '#FAFAFA',
      '--color-foreground':        '#5C6166',
      '--color-card':              '#FFFFFF',
      '--color-card-foreground':   '#5C6166',
      '--color-primary':           '#FF9940',
      '--color-primary-foreground':'#FAFAFA',
      '--color-secondary':         '#F0F0F0',
      '--color-secondary-foreground':'#5C6166',
      '--color-muted':             '#F0F0F0',
      '--color-muted-foreground':  '#8A9199',
      '--color-destructive':       '#F07171',
      '--color-border':            '#E0E0E0',
      '--color-input':             '#E0E0E0',
      '--color-ring':              '#FF9940',
      '--color-green':             '#86B300',
      '--color-red':               '#F07171',
      '--color-orange':            '#FF9940',
      '--color-purple':            '#A37ACC',
      '--color-scrollbar':         '#D8D8D8',
      '--color-scrollbar-hover':   '#B8B8B8',
    },
  },
  'rose-pine-dawn': {
    name: 'rose-pine-dawn',
    label: 'Rosé Pine Dawn',
    colors: {
      '--color-background':        '#FAF4ED',
      '--color-foreground':        '#575279',
      '--color-card':              '#FFFAF3',
      '--color-card-foreground':   '#575279',
      '--color-primary':           '#907AA9',
      '--color-primary-foreground':'#FAF4ED',
      '--color-secondary':         '#F2E9E1',
      '--color-secondary-foreground':'#575279',
      '--color-muted':             '#F2E9E1',
      '--color-muted-foreground':  '#9893A5',
      '--color-destructive':       '#B4637A',
      '--color-border':            '#DFDAD9',
      '--color-input':             '#DFDAD9',
      '--color-ring':              '#907AA9',
      '--color-green':             '#56949F',
      '--color-red':               '#B4637A',
      '--color-orange':            '#EA9D34',
      '--color-purple':            '#907AA9',
      '--color-scrollbar':         '#DFDAD9',
      '--color-scrollbar-hover':   '#CEC9C6',
    },
  },
  'gruvbox-light': {
    name: 'gruvbox-light',
    label: 'Gruvbox Light',
    colors: {
      '--color-background':        '#FBF1C7',
      '--color-foreground':        '#3C3836',
      '--color-card':              '#F2E5BC',
      '--color-card-foreground':   '#3C3836',
      '--color-primary':           '#D65D0E',
      '--color-primary-foreground':'#FBF1C7',
      '--color-secondary':         '#EBDBB2',
      '--color-secondary-foreground':'#3C3836',
      '--color-muted':             '#EBDBB2',
      '--color-muted-foreground':  '#7C6F64',
      '--color-destructive':       '#CC241D',
      '--color-border':            '#D5C4A1',
      '--color-input':             '#D5C4A1',
      '--color-ring':              '#D65D0E',
      '--color-green':             '#79740E',
      '--color-red':               '#CC241D',
      '--color-orange':            '#D65D0E',
      '--color-purple':            '#8F3F71',
      '--color-scrollbar':         '#D5C4A1',
      '--color-scrollbar-hover':   '#BDAE93',
    },
  },
  'one-light': {
    name: 'one-light',
    label: 'One Light',
    colors: {
      '--color-background':        '#FAFAFA',
      '--color-foreground':        '#383A42',
      '--color-card':              '#FFFFFF',
      '--color-card-foreground':   '#383A42',
      '--color-primary':           '#4078F2',
      '--color-primary-foreground':'#FFFFFF',
      '--color-secondary':         '#F0F0F0',
      '--color-secondary-foreground':'#383A42',
      '--color-muted':             '#F0F0F0',
      '--color-muted-foreground':  '#A0A1A7',
      '--color-destructive':       '#E45649',
      '--color-border':            '#E0E0E0',
      '--color-input':             '#E0E0E0',
      '--color-ring':              '#4078F2',
      '--color-green':             '#50A14F',
      '--color-red':               '#E45649',
      '--color-orange':            '#C18401',
      '--color-purple':            '#A626A4',
      '--color-scrollbar':         '#D4D4D4',
      '--color-scrollbar-hover':   '#B4B4B4',
    },
  },
  'everforest-light': {
    name: 'everforest-light',
    label: 'Everforest Light',
    colors: {
      '--color-background':        '#FDF6E3',
      '--color-foreground':        '#5C6A72',
      '--color-card':              '#F3EAD3',
      '--color-card-foreground':   '#5C6A72',
      '--color-primary':           '#8DA101',
      '--color-primary-foreground':'#FDF6E3',
      '--color-secondary':         '#EFE4CA',
      '--color-secondary-foreground':'#5C6A72',
      '--color-muted':             '#EFE4CA',
      '--color-muted-foreground':  '#939F91',
      '--color-destructive':       '#F85552',
      '--color-border':            '#D5C4A1',
      '--color-input':             '#D5C4A1',
      '--color-ring':              '#8DA101',
      '--color-green':             '#8DA101',
      '--color-red':               '#F85552',
      '--color-orange':            '#DFA000',
      '--color-purple':            '#DF69BA',
      '--color-scrollbar':         '#D5C4A1',
      '--color-scrollbar-hover':   '#C4B393',
    },
  },
  'nord-light': {
    name: 'nord-light',
    label: 'Nord Light',
    colors: {
      '--color-background':        '#ECEFF4',
      '--color-foreground':        '#2E3440',
      '--color-card':              '#E5E9F0',
      '--color-card-foreground':   '#2E3440',
      '--color-primary':           '#5E81AC',
      '--color-primary-foreground':'#ECEFF4',
      '--color-secondary':         '#D8DEE9',
      '--color-secondary-foreground':'#2E3440',
      '--color-muted':             '#D8DEE9',
      '--color-muted-foreground':  '#4C566A',
      '--color-destructive':       '#BF616A',
      '--color-border':            '#D8DEE9',
      '--color-input':             '#D8DEE9',
      '--color-ring':              '#5E81AC',
      '--color-green':             '#A3BE8C',
      '--color-red':               '#BF616A',
      '--color-orange':            '#D08770',
      '--color-purple':            '#B48EAD',
      '--color-scrollbar':         '#D8DEE9',
      '--color-scrollbar-hover':   '#C2CAD6',
    },
  },

  /* ── Mid-brightness themes ────────────────────────────── */

  'catppuccin-frappe': {
    name: 'catppuccin-frappe',
    label: 'Catppuccin Frappé',
    colors: {
      '--color-background':        '#303446',
      '--color-foreground':        '#C6D0F5',
      '--color-card':              '#292C3C',
      '--color-card-foreground':   '#C6D0F5',
      '--color-primary':           '#CA9EE6',
      '--color-primary-foreground':'#303446',
      '--color-secondary':         '#414559',
      '--color-secondary-foreground':'#C6D0F5',
      '--color-muted':             '#414559',
      '--color-muted-foreground':  '#838BA7',
      '--color-destructive':       '#E78284',
      '--color-border':            '#414559',
      '--color-input':             '#414559',
      '--color-ring':              '#CA9EE6',
      '--color-green':             '#A6D189',
      '--color-red':               '#E78284',
      '--color-orange':            '#EF9F76',
      '--color-purple':            '#CA9EE6',
      '--color-scrollbar':         '#414559',
      '--color-scrollbar-hover':   '#51576D',
    },
  },
  'catppuccin-macchiato': {
    name: 'catppuccin-macchiato',
    label: 'Catppuccin Macchiato',
    colors: {
      '--color-background':        '#24273A',
      '--color-foreground':        '#CAD3F5',
      '--color-card':              '#1E2030',
      '--color-card-foreground':   '#CAD3F5',
      '--color-primary':           '#C6A0F6',
      '--color-primary-foreground':'#24273A',
      '--color-secondary':         '#363A4F',
      '--color-secondary-foreground':'#CAD3F5',
      '--color-muted':             '#363A4F',
      '--color-muted-foreground':  '#8087A2',
      '--color-destructive':       '#ED8796',
      '--color-border':            '#363A4F',
      '--color-input':             '#363A4F',
      '--color-ring':              '#C6A0F6',
      '--color-green':             '#A6DA95',
      '--color-red':               '#ED8796',
      '--color-orange':            '#F5A97F',
      '--color-purple':            '#C6A0F6',
      '--color-scrollbar':         '#363A4F',
      '--color-scrollbar-hover':   '#494D64',
    },
  },
  'rose-pine-moon': {
    name: 'rose-pine-moon',
    label: 'Rosé Pine Moon',
    colors: {
      '--color-background':        '#232136',
      '--color-foreground':        '#E0DEF4',
      '--color-card':              '#2A273F',
      '--color-card-foreground':   '#E0DEF4',
      '--color-primary':           '#C4A7E7',
      '--color-primary-foreground':'#232136',
      '--color-secondary':         '#393552',
      '--color-secondary-foreground':'#E0DEF4',
      '--color-muted':             '#393552',
      '--color-muted-foreground':  '#817C9C',
      '--color-destructive':       '#EB6F92',
      '--color-border':            '#393552',
      '--color-input':             '#393552',
      '--color-ring':              '#C4A7E7',
      '--color-green':             '#9CCFD8',
      '--color-red':               '#EB6F92',
      '--color-orange':            '#F6C177',
      '--color-purple':            '#C4A7E7',
      '--color-scrollbar':         '#393552',
      '--color-scrollbar-hover':   '#44395B',
    },
  },
};

export const themeNames = Object.keys(themes) as ThemeName[];

const lightThemes: ReadonlySet<ThemeName> = new Set([
  'light', 'github-light', 'solarized-light', 'catppuccin-latte',
  'ayu-light', 'rose-pine-dawn', 'gruvbox-light', 'one-light',
  'everforest-light', 'nord-light',
]);

export function isLightTheme(themeName: ThemeName): boolean {
  return lightThemes.has(themeName);
}

/**
 * Apply a theme by writing its CSS variables onto the document root.
 *
 * Mercury V2 components consume `text-theme-green`, `bg-theme-amber`, etc.
 * (declared in src/index.css `@theme` block). The Mastermind catalog ships
 * the plain `--color-green/red/orange/purple` names, so we also write
 * theme-prefixed aliases on top — and alias `--color-theme-amber` to the
 * theme's orange (no native amber in the catalog).
 */
export function applyTheme(themeName: ThemeName): void {
  const theme = themes[themeName];
  if (!theme) return;
  const root = document.documentElement;
  for (const [prop, val] of Object.entries(theme.colors)) {
    root.style.setProperty(prop, val);
  }
  const c = theme.colors;
  const set = (name: string, val: string | undefined) => { if (val) root.style.setProperty(name, val); };
  set('--color-theme-green',  c['--color-green']);
  set('--color-theme-red',    c['--color-red']);
  set('--color-theme-orange', c['--color-orange']);
  set('--color-theme-purple', c['--color-purple']);
  set('--color-theme-amber',  c['--color-orange']);
  root.style.setProperty('color-scheme', lightThemes.has(themeName) ? 'light' : 'dark');
}
