"""Routes admin benchmarks externes (ToolCall-15, BugFind-15, etc.).
Proxy generique Next.js + sync .env + import resultats dans benchmark.json."""
import json
import logging
from pathlib import Path
from typing import Any

import httpx
from fastapi import APIRouter
from fastapi.responses import JSONResponse

from routing.router import get_config

logger = logging.getLogger(__name__)
router = APIRouter()

_ROOT = Path(__file__).resolve().parent.parent.parent  # MERCURY/

# ---------------------------------------------------------------------------
# Registry of external benchmarks
# ---------------------------------------------------------------------------

_BENCHMARKS = {
    "toolcall15": {
        "label": "ToolCall-15",
        "dir": "toolcall15",
        "config_enabled": "toolcall15_enabled",
        "config_url": "toolcall15_url",
        "default_port": 3015,
        "extra_env": "",
    },
    "bugfind15": {
        "label": "BugFind-15",
        "dir": "bugfind15",
        "config_enabled": "bugfind15_enabled",
        "config_url": "bugfind15_url",
        "default_port": 3016,
        "extra_env": "BUGFIND_SANDBOX_URL=http://127.0.0.1:4010\nBUGFIND_SANDBOX_TIMEOUT_MS=30000\n",
    },
}


def _get_bench_base(bench_id: str) -> str:
    config = get_config()
    meta = _BENCHMARKS.get(bench_id)
    if not meta:
        return ""
    if not config.get(meta["config_enabled"], False):
        return ""
    default = f"http://localhost:{meta['default_port']}"
    return str(config.get(meta["config_url"], default)).rstrip("/")


def _get_bench_dir(bench_id: str) -> Path:
    meta = _BENCHMARKS.get(bench_id)
    if not meta:
        return _ROOT / bench_id
    return _ROOT / meta["dir"]


def _llamacpp_base() -> str:
    config = get_config()
    return str(config.get("llamacpp_url", "http://localhost:4321")).rstrip("/")


# ---------------------------------------------------------------------------
# Sync .env — shared logic for all external benchmarks
# ---------------------------------------------------------------------------


async def _sync_env(bench_id: str, selected_models: list[str] | None = None) -> dict:
    meta = _BENCHMARKS.get(bench_id)
    if not meta:
        return {"error": f"Benchmark '{bench_id}' inconnu"}

    daemon_url = _llamacpp_base()
    if not daemon_url:
        return {"error": "llamacpp non configure"}

    if selected_models:
        # Use user-selected models
        ready_models = selected_models
    else:
        # Fallback: fetch all loaded models from daemon
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.get(f"{daemon_url}/mgmt/status")
            instances = resp.json()
        except Exception as e:
            return {"error": f"Daemon inaccessible: {e}"}
        ready_models = [i["model_id"] for i in instances if i.get("ready")]

    if not ready_models:
        return {"error": "Aucun modele selectionne"}

    bench_dir = _get_bench_dir(bench_id)
    if not bench_dir.exists():
        return {"error": f"Dossier {bench_dir} introuvable"}

    llm_models = ",".join(f"llamacpp:{m}" for m in ready_models)
    env_content = f"# Auto-generated by Mercury\nLLAMACPP_HOST={daemon_url}\nLLM_MODELS={llm_models}\nMODEL_REQUEST_TIMEOUT_SECONDS=600\n{meta['extra_env']}"

    env_path = bench_dir / ".env"
    env_path.write_text(env_content, encoding="utf-8")
    logger.info("[%s] .env synced: %d models, daemon=%s", bench_id, len(ready_models), daemon_url)

    return {"ok": True, "daemon_url": daemon_url, "models": ready_models, "llm_models": llm_models}


async def _get_status(bench_id: str) -> dict:
    base = _get_bench_base(bench_id)
    service_ok = False
    if base:
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                resp = await client.get(base)
            service_ok = resp.status_code == 200
        except Exception:
            pass

    bench_dir = _get_bench_dir(bench_id)
    env_path = bench_dir / ".env"
    current_models: list[str] = []
    current_daemon = ""
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("LLM_MODELS="):
                raw = line.split("=", 1)[1]
                current_models = [m.replace("llamacpp:", "") for m in raw.split(",") if m.strip()]
            elif line.startswith("LLAMACPP_HOST="):
                current_daemon = line.split("=", 1)[1].strip()

    meta = _BENCHMARKS.get(bench_id, {})
    proc = _bench_processes.get(bench_id)
    managed = proc is not None and proc.returncode is None
    return {
        "bench_id": bench_id,
        "label": meta.get("label", bench_id),
        "enabled": bool(base),
        "service_online": service_ok,
        "service_url": base,
        "env_exists": env_path.exists(),
        "configured_models": current_models,
        "configured_daemon": current_daemon,
        "bench_dir": str(bench_dir),
        "default_port": meta.get("default_port"),
        "managed_pid": proc.pid if managed else None,
    }


# ---------------------------------------------------------------------------
# Routes — generated for each benchmark
# ---------------------------------------------------------------------------


# ── ToolCall-15 ───────────────────────────────────────────────────────────────

@router.post("/toolcall15/sync-env")
async def tc15_sync(body: dict = None):
    models = (body or {}).get("models")
    r = await _sync_env("toolcall15", models)
    return JSONResponse(r, status_code=200 if r.get("ok") else 503)

@router.get("/toolcall15/status")
async def tc15_status():
    return await _get_status("toolcall15")

# ── Service start/stop ────────────────────────────────────────────────────────

import asyncio
import signal

_bench_processes: dict[str, asyncio.subprocess.Process] = {}

# Verrou par bench_id : le check-then-act (returncode is None -> spawn -> stockage du
# handle) traverse un `await` (create_subprocess_exec). Sans verrou, deux /start
# concurrents passent tous deux le check "pas lance" et le 2e ecrase/orpheline le
# process du 1er. Lazy-init (cf request_queue) pour ne pas lier le Lock a une loop
# a l'import. La lecture du dict est synchrone (pas d'await) -> setdefault sans race.
_start_locks: dict[str, asyncio.Lock] = {}


def _get_start_lock(bench_id: str) -> asyncio.Lock:
    return _start_locks.setdefault(bench_id, asyncio.Lock())


@router.post("/ext-bench/{bench_id}/start")
async def start_service(bench_id: str):
    """Demarre le service Next.js d'un benchmark externe."""
    meta = _BENCHMARKS.get(bench_id)
    if not meta:
        return JSONResponse({"error": f"Benchmark '{bench_id}' inconnu"}, status_code=404)

    # Serialise le check-then-act par service : un seul /start progresse a la fois.
    async with _get_start_lock(bench_id):
        if bench_id in _bench_processes and _bench_processes[bench_id].returncode is None:
            return {"ok": True, "status": "already_running", "pid": _bench_processes[bench_id].pid}

        return await _spawn_service(bench_id, meta)


async def _spawn_service(bench_id: str, meta: dict) -> Any:
    """Spawn effectif du service — appele sous _get_start_lock(bench_id)."""
    bench_dir = _get_bench_dir(bench_id)
    if not bench_dir.exists() or not (bench_dir / "package.json").exists():
        return JSONResponse({"error": f"Dossier {bench_dir} introuvable ou pas de package.json"}, status_code=404)

    port = meta["default_port"]
    logger.info("[%s] starting service on port %d...", bench_id, port)

    # Le serveur dev Next.js est long-running et tres bavard (compile/HMR/req).
    # On NE peut PAS laisser stdout sur PIPE sans le drainer : le buffer OS (~64KB)
    # se remplit et le child bloque en ecriture -> service fige. On redirige donc
    # vers un fichier de log (le write fichier ne bloque pas comme un pipe) ce qui
    # draine la sortie ET garde les logs pour debug.
    log_path = bench_dir / "dev-server.log"
    log_fh = None
    try:
        log_fh = open(log_path, "ab")  # noqa: SIM115 — drainage stdout, ferme juste apres spawn
        proc = await asyncio.create_subprocess_exec(
            "npm", "run", "dev", "--", "-p", str(port),
            cwd=str(bench_dir),
            stdout=log_fh,
            stderr=asyncio.subprocess.STDOUT,
        )
        _bench_processes[bench_id] = proc
        logger.info("[%s] service started pid=%d port=%d log=%s", bench_id, proc.pid, port, log_path)
        return {"ok": True, "status": "started", "pid": proc.pid, "port": port}
    except Exception as e:
        logger.error("[%s] failed to start: %s", bench_id, e)
        return JSONResponse({"error": f"Erreur demarrage: {e}"}, status_code=500)
    finally:
        # Le child a herite du fd ; on ferme notre copie (y compris si spawn echoue).
        if log_fh is not None:
            log_fh.close()


@router.post("/ext-bench/{bench_id}/stop")
async def stop_service(bench_id: str):
    """Arrete le service Next.js d'un benchmark externe."""
    meta = _BENCHMARKS.get(bench_id)
    if not meta:
        return JSONResponse({"error": f"Benchmark '{bench_id}' inconnu"}, status_code=404)

    # Try managed process first
    proc = _bench_processes.get(bench_id)
    if proc and proc.returncode is None:
        logger.info("[%s] stopping managed service pid=%d...", bench_id, proc.pid)
        try:
            proc.terminate()
            try:
                await asyncio.wait_for(proc.wait(), timeout=5.0)
            except asyncio.TimeoutError:
                proc.kill()
                await proc.wait()
        except Exception as e:
            logger.error("[%s] error stopping managed process: %s", bench_id, e)
        _bench_processes.pop(bench_id, None)
        logger.info("[%s] managed service stopped", bench_id)
        return {"ok": True, "status": "stopped"}

    # Fallback: kill whatever is listening on the port (started manually)
    port = meta["default_port"]
    logger.info("[%s] no managed process, killing port %d...", bench_id, port)
    try:
        kill_proc = await asyncio.create_subprocess_exec(
            "fuser", "-k", f"{port}/tcp",
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        await asyncio.wait_for(kill_proc.wait(), timeout=5.0)
        logger.info("[%s] killed process on port %d", bench_id, port)
        _bench_processes.pop(bench_id, None)
        return {"ok": True, "status": "stopped", "method": "fuser"}
    except FileNotFoundError:
        # fuser not available, try lsof + kill
        try:
            lsof_proc = await asyncio.create_subprocess_exec(
                "lsof", "-ti", f":{port}",
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            stdout, _ = await asyncio.wait_for(lsof_proc.communicate(), timeout=5.0)
            pids = stdout.decode().strip().split()
            for pid in pids:
                if pid.isdigit():
                    kill_p = await asyncio.create_subprocess_exec("kill", pid)
                    await kill_p.wait()
            logger.info("[%s] killed pids %s on port %d", bench_id, pids, port)
            _bench_processes.pop(bench_id, None)
            return {"ok": True, "status": "stopped", "method": "lsof", "pids": pids}
        except Exception as e2:
            logger.error("[%s] fallback kill failed: %s", bench_id, e2)
            _bench_processes.pop(bench_id, None)
            return JSONResponse({"error": f"Impossible d'arreter le service sur le port {port}: {e2}"}, status_code=500)
    except Exception as e:
        logger.error("[%s] fuser kill failed: %s", bench_id, e)
        _bench_processes.pop(bench_id, None)
        return JSONResponse({"error": f"Erreur arret: {e}"}, status_code=500)


# ── BugFind-15 sandbox Docker ─────────────────────────────────────────────────

_sandbox_process: asyncio.subprocess.Process | None = None


@router.get("/bugfind15/sandbox-status")
async def bf15_sandbox_status():
    """Verifie si le sandbox Docker BugFind-15 tourne."""
    sandbox_ok = False
    try:
        async with httpx.AsyncClient(timeout=3.0) as client:
            resp = await client.get("http://127.0.0.1:4010/health")
        sandbox_ok = resp.status_code == 200
    except Exception:
        # Try a simple connect
        try:
            async with httpx.AsyncClient(timeout=3.0) as client:
                resp = await client.post("http://127.0.0.1:4010/verify-answer", json={"test": True})
            sandbox_ok = True  # Any response means it's running
        except Exception:
            pass

    global _sandbox_process
    managed = _sandbox_process is not None and _sandbox_process.returncode is None
    return {"online": sandbox_ok, "managed": managed, "pid": _sandbox_process.pid if managed else None}


@router.post("/bugfind15/sandbox-start")
async def bf15_sandbox_start():
    """Lance le sandbox Docker BugFind-15."""
    global _sandbox_process

    if _sandbox_process and _sandbox_process.returncode is None:
        return {"ok": True, "status": "already_running", "pid": _sandbox_process.pid}

    bench_dir = _get_bench_dir("bugfind15")
    if not bench_dir.exists():
        return JSONResponse({"error": "Dossier bugfind15 introuvable"}, status_code=404)

    logger.info("[bugfind15] starting sandbox...")
    # Meme piege que le dev-server : process long-running, sortie jamais lue.
    # PIPE non draine -> buffer OS plein -> child bloque. On redirige vers fichier.
    log_path = bench_dir / "sandbox-serve.log"
    log_fh = None
    try:
        log_fh = open(log_path, "ab")  # noqa: SIM115 — drainage stdout, ferme juste apres spawn
        proc = await asyncio.create_subprocess_exec(
            "npm", "run", "verify:sandbox:serve",
            cwd=str(bench_dir),
            stdout=log_fh,
            stderr=asyncio.subprocess.STDOUT,
        )
        _sandbox_process = proc
        logger.info("[bugfind15] sandbox started pid=%d log=%s", proc.pid, log_path)
        return {"ok": True, "status": "started", "pid": proc.pid}
    except Exception as e:
        logger.error("[bugfind15] sandbox start failed: %s", e)
        return JSONResponse({"error": f"Erreur: {e}"}, status_code=500)
    finally:
        # Le child a herite du fd ; on ferme notre copie (y compris si spawn echoue).
        if log_fh is not None:
            log_fh.close()


@router.post("/bugfind15/sandbox-stop")
async def bf15_sandbox_stop():
    """Arrete le sandbox Docker BugFind-15."""
    global _sandbox_process

    # Try managed process
    if _sandbox_process and _sandbox_process.returncode is None:
        _sandbox_process.terminate()
        try:
            await asyncio.wait_for(_sandbox_process.wait(), timeout=5.0)
        except asyncio.TimeoutError:
            _sandbox_process.kill()
        _sandbox_process = None

    # Also run npm run verify:sandbox:stop to clean up Docker
    bench_dir = _get_bench_dir("bugfind15")
    if bench_dir.exists():
        try:
            stop_proc = await asyncio.create_subprocess_exec(
                "npm", "run", "verify:sandbox:stop",
                cwd=str(bench_dir),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            await asyncio.wait_for(stop_proc.wait(), timeout=10.0)
            logger.info("[bugfind15] sandbox stopped")
        except Exception as e:
            logger.warning("[bugfind15] sandbox stop cleanup: %s", e)

    return {"ok": True, "status": "stopped"}


# ── BugFind-15 (auth-protected) ───────────────────────────────────────────────

@router.post("/bugfind15/sync-env")
async def bf15_sync(body: dict = None):
    models = (body or {}).get("models")
    r = await _sync_env("bugfind15", models)
    return JSONResponse(r, status_code=200 if r.get("ok") else 503)

@router.get("/bugfind15/status")
async def bf15_status():
    return await _get_status("bugfind15")


# ── List all available external benchmarks ────────────────────────────────────

@router.get("/ext-bench/list")
async def list_benchmarks():
    results = []
    for bench_id in _BENCHMARKS:
        results.append(await _get_status(bench_id))
    return {"benchmarks": results}
